# 基本となるイメージを指定
FROM ruby:3.2.3
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# パッケージリストを更新し、依存関係をインストール
RUN apt-get update -qq \
    && apt-get install -y ca-certificates curl gnupg \
    && mkdir -p /etc/apt/keyrings

# Node.jsのセットアップとGPGキーの追加
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && NODE_MAJOR=18 \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

# YarnのセットアップとGPGキーの追加
RUN curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor -o /etc/apt/keyrings/yarn.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/yarn.gpg] https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# Node.jsとYarnのインストールを完了
RUN apt-get update -qq \
    && apt-get install -y build-essential libpq-dev nodejs yarn vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# アプリケーションディレクトリを設定
RUN mkdir -p /myapp
WORKDIR /myapp
COPY . /myapp

# Bundlerのインストール
RUN gem install bundler